package window.inputs;

import static org.lwjgl.glfw.GLFW.*;

public class KeyCodes {

	public static final int
			MOUSE_MOVE_LEFT = 200,
			MOUSE_MOVE_RIGHT = 201,
			MOUSE_MOVE_UP = 202,
			MOUSE_MOVE_DOWN = 203;


	public static final int
			GAMEPAD_1_BUTTON_A = 100  + GLFW_GAMEPAD_BUTTON_A,
			GAMEPAD_1_BUTTON_B = 100  + GLFW_GAMEPAD_BUTTON_B,
			GAMEPAD_1_BUTTON_X = 100  + GLFW_GAMEPAD_BUTTON_X,
			GAMEPAD_1_BUTTON_Y = 100  + GLFW_GAMEPAD_BUTTON_Y,
			GAMEPAD_1_BUTTON_LEFT_BUMPER = 100  + GLFW_GAMEPAD_BUTTON_LEFT_BUMPER,
			GAMEPAD_1_BUTTON_RIGHT_BUMPER = 100  + GLFW_GAMEPAD_BUTTON_RIGHT_BUMPER,
			GAMEPAD_1_BUTTON_BACK = 100  + GLFW_GAMEPAD_BUTTON_BACK,
			GAMEPAD_1_BUTTON_START = 100  + GLFW_GAMEPAD_BUTTON_START,
			GAMEPAD_1_BUTTON_GUIDE = 100  + GLFW_GAMEPAD_BUTTON_GUIDE,
			GAMEPAD_1_BUTTON_LEFT_THUMB = 100  + GLFW_GAMEPAD_BUTTON_LEFT_THUMB,
			GAMEPAD_1_BUTTON_RIGHT_THUMB = 100  + GLFW_GAMEPAD_BUTTON_RIGHT_THUMB,
			GAMEPAD_1_BUTTON_DPAD_UP = 100  + GLFW_GAMEPAD_BUTTON_DPAD_UP,
			GAMEPAD_1_BUTTON_DPAD_RIGHT = 100  + GLFW_GAMEPAD_BUTTON_DPAD_RIGHT,
			GAMEPAD_1_BUTTON_DPAD_DOWN = 100  + GLFW_GAMEPAD_BUTTON_DPAD_DOWN,
			GAMEPAD_1_BUTTON_DPAD_LEFT = 100  + GLFW_GAMEPAD_BUTTON_DPAD_LEFT;

	public static final int
			GAMEPAD_1_LEFT_AXIS_LEFT = 115 + GLFW_GAMEPAD_AXIS_LEFT_X,
			GAMEPAD_1_LEFT_AXIS_UP = 115 + GLFW_GAMEPAD_AXIS_LEFT_Y,
			GAMEPAD_1_RIGHT_AXIS_LEFT = 115 + GLFW_GAMEPAD_AXIS_RIGHT_X,
			GAMEPAD_1_RIGHT_AXIS_UP = 115 + GLFW_GAMEPAD_AXIS_RIGHT_Y,
			GAMEPAD_1_LEFT_TRIGGER = 115 + GLFW_GAMEPAD_AXIS_LEFT_TRIGGER,
			GAMEPAD_1_RIGHT_TRIGGER = 115 + GLFW_GAMEPAD_AXIS_RIGHT_TRIGGER,
			GAMEPAD_1_LEFT_AXIS_RIGHT = 121 + GLFW_GAMEPAD_AXIS_LEFT_X,
			GAMEPAD_1_LEFT_AXIS_DOWN = 121 + GLFW_GAMEPAD_AXIS_LEFT_Y,
			GAMEPAD_1_RIGHT_AXIS_RIGHT = 121 + GLFW_GAMEPAD_AXIS_RIGHT_X,
			GAMEPAD_1_RIGHT_AXIS_DOWN = 121 + GLFW_GAMEPAD_AXIS_RIGHT_Y;

}
